#!/usr/bin/env bash

# SYNOPSIS:
#   ./install [OPTIONS]
#
# DESCRIPTION:
#   OPTIONS:
#       --prefix <prefix>
#           where to install SIU
#       --help, -h
#           print helper

script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "$script_dir" || {
    echo "Could not cd into $script_dir (should be SIU's root directory)."
    exit 1
}

# TODO: get SIU_PREFIX from argument (default: $HOME) and overwrite it in env_siu.sh

export SIU_PREFIX="${HOME}"

(
    . src/source_all.sh
    _siu::log::info "Starting SIU installation in '${SIU_DIR}'."

    if [[ -d "${SIU_DIR}" ]]; then
        _siu::log::error "SIU directory '${SIU_DIR}' already exist. Stopping installation."
        exit 1
    fi

    mv "${PWD}" "${SIU_DIR}" || {
        _siu::log::error "Could not create SIU directory '${SIU_DIR}'. Stopping installation."
        exit 1
    }

    _siu::setup::init_siu

    ln -s "$(realpath "${SIU_DIR}/siu")" "${SIU_BIN_DIR}/siu"
    _siu::log::info "SIU has been installed in '${SIU_DIR}'."
)
